theme: minima
title: A Short Story
author: Jerry Foster
email: jlfoster@rocketmail.com
description: > # this means to ignore newlines until "baseurl:"
   This is the tale of a tall man.  Or perhaps the tall tale of a short man...

# social links
github_username:  jlfosterjr # DO NOT include the @ character, or else the build will fail!
linkedin_username:  jlfoster

show_excerpts: true # set to false to remove excerpts on the homepage
